packages:
  - "apps/*"
  - "packages/*"

autoInstallPeers: false

overrides:
  parse5: "^7.2.1"

allowBuilds:
  '@clerk/shared': false
  "@prisma/client": true
  "@prisma/engines": true
  '@sentry/cli': false
  bufferutil: false
  core-js: false
  core-js-pure: false
  esbuild: true
  prisma: true
  sharp: true
